server:
  port: 8080

jwt:
  secret: bu-benim-cok-guclu-ve-uzun-secret-key-degerim-32-karakter

spring:
  cloud:
    gateway:
      routes:
        # Auth Service Rotası
        - id: auth-service-route
          uri: lb://auth-service
          predicates:
            - Path=/auth/**

        # User Service Rotası
        - id: user-service-route
          uri: lb://user-service
          predicates:
            - Path=/users/**

        # Order Service Rotası
        - id: order-service-route
          uri: lb://order-service
          predicates:
            - Path=/orders/**

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
